name: Build one .zip (and upload)

on:
  workflow_dispatch:
    inputs:
      tileset:
        type: choice
        options:
          - asi
          - afr
          - sa
          - na
          - aus_pac
          - eur
          - test  
      zl:
        type: string
        default: 16
      relname:
        type: string
        default: ''
      zipnum:
        type: string
        required: true

jobs:
  call-build:
    uses: ./.github/workflows/build-tiles.yml
    with:
      zip: z_${{ inputs.tileset }}_${{ inputs.zipnum }}.zip
      setname: ${{ inputs.tileset }}
      relname: ${{ inputs.relname }} 
